Add addTA as instructor unit tests
MWHunter/schedulingApp pull request #44
Opened 2022-12-16 23:12 UTC by msladwig

Adding unit tests for assuring professor is assigned to course, has proper permissions, and is able to assign a TA.

I expect these unit tests to change, perhaps drastically, as we explore/set implementation details.

2022-12-18 21:04 UTC, Svedek requested changes

2022-12-18 21:04 UTC, Svedek commented on schedulingApp/unit-tests/test_sections.py
> +        self.assertFalse(self.profProfile in self.course.getAllProfiles(),
if the first line of your test_assignTAValid test passes, this one will fail

2022-12-18 21:04 UTC, Svedek commented on schedulingApp/unit-tests/test_sections.py
> +        self.assertFalse(self.profProfile in self.course.getAllProfiles(),
same issue for line 2 of test_setTANotAssignedInvalidPermissions

2022-12-20 20:59 UTC, msladwig commented
Fixed issues with unit testing; Are you able to re-review when you have the opportunity?

2022-12-20 21:47 UTC, merged